### ISSUE TITLE
Test task issues

### ISSUE THREAD

**Issue by Sohaib404** [CMPUT301F21T19/Bean-Team#7]
## Tasks

- [ ]  Test Cases for Adding Habit
- [ ] Test Cases for deleting Habit
- [ ] Test Cases for Adding Habit Event
